[versions]
accompanist = "0.30.1"
agp = "8.0.2"
bouncycastle = "1.75"
bundletool-plugin = "0.1.2"
coil = "2.4.0"
compose-bom = "2023.05.01"
compose-lint = "1.2.0"
dagger = "2.46.1"
datastore = "1.0.0"
hilt = "1.0.0"
immutable = "0.3.5"
kotlin = "1.8.22"
ksp = "1.8.22-1.0.11"
lifecycle = "2.6.1"
material = "1.9.0"
nav-compose = "2.5.3"
room = "2.5.1"
serialization = "1.5.1"
work = "2.8.1"

[libraries]
accompanist-navanimation = { group = "com.google.accompanist", name = "accompanist-navigation-animation", version.ref = "accompanist" }
accompanist-systemuicontroller = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "accompanist" }
bouncycastle = { group = "org.bouncycastle", name = "bcprov-jdk18on", version.ref = "bouncycastle" }
coil = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
compose-lint = { group = "com.slack.lint.compose", name = "compose-lint-checks", version.ref = "compose-lint" }
compose-material = { group = "androidx.compose.material", name = "material" }
compose-material-icons = { group = "androidx.compose.material", name = "material-icons-extended" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
dagger = { group = "com.google.dagger", name = "hilt-android", version.ref = "dagger" }
dagger-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "dagger" }
datastore = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }
hilt-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "hilt" }
hilt-navcompose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hilt" }
hilt-work = { group = "androidx.hilt", name = "hilt-work", version.ref = "hilt" }
immutable = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "immutable" }
lifecycle-process = { group = "androidx.lifecycle", name = "lifecycle-process", version.ref = "lifecycle" }
lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
navcompose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "nav-compose" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
serialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization" }
work-runtime = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "work" }

[plugins]
accrescent-bundletool = { id = "app.accrescent.tools.bundletool", version.ref = "bundletool-plugin" }
android-application = { id = "com.android.application", version.ref = "agp" }
dagger = { id = "com.google.dagger.hilt.android", version.ref = "dagger" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
